name: build-env
channels:
  - https://prefix.dev/emscripten-forge-dev
  - conda-forge
dependencies:
  - python =3.13
  - pip
  - jupyter_server
  - jupyterlite-core
  - pip:
    - jupyterlite-xeus ==3.1.3
