name: xeus-python-kernel
channels:
  - https://prefix.dev/emscripten-forge-dev
  - conda-forge
dependencies:
  - python
  - pip
  - xeus-python
  - jupytergis_lab =0.3.0
  - emscripten-abi =3.1.73
  - pip:
    - my-jupyter-shared-drive ==0.1.5
